services:
  db:
    image: postgres:17
    container_name: guia-parcerias-db
    environment:
      POSTGRES_USER: guia
      POSTGRES_PASSWORD: guia
      POSTGRES_DB: guia
    ports:
      - '5433:5432'
    volumes:
      - dados:/var/lib/postgresql/data

volumes:
  dados:
